### ISSUE TITLE
App gets suspended in background and stops updating location after 10min

### ISSUE THREAD

**Issue by O-mkar** [paleksandrs/APScheduledLocationManager#11]
I used this for getting the location in background but when app goes to background it only updates location for 8-10min after that if won't event update or give any location changes something is not keeping app alive I guess it is suspended I also tried with example app

manager.startUpdatingLocation(interval: 10, acceptableLocationAccuracy: 100)

**Comment by bart-kneepkens** [comment]
I think it happens because iOS is not providing a location with <100m accuracy. Therefore APScheduledLocationManager will not fire.  As said in the ReadMe, the manager will wait for a location in this case.
