### ISSUE TITLE
LocationManager can't be stopped

### ISSUE THREAD

**Issue by iloveivyxuan** [paleksandrs/APScheduledLocationManager#13]
In your Demo Project, I changed just 1 line of code:
```swift
manager.startUpdatingLocation(interval: 2, acceptableLocationAccuracy: 100)
```
I ran the Demo App and clicked the `stop` button when the App collected more than 5 location record, then I found that the App didn't stop, it still push new location records to the text view.
But when I click the `stop` button right after a new record pushed onto the screen, sometimes it can be stopped successfully.
I added some debug print code to the functions like `startWaitTimer()`, `stopWaitTimer()`, `startCheckLocationTimer()` and `stopCheckLocationTimer()`, then found that if I click just before the wait timer starts, it can be stopped successfully, but once the wait timer starts, the `stoptUpdatingLocation()` function can't truly stop the timer loop.

**Comment by iloveivyxuan** [comment]
@paleksandrs Sorry to bother you, but I really want to know whether this issue can be solved.

**Comment by paleksandrs** [comment]
@iloveivyxuan issue should be fixed now. Please update the pod and let me know if everything works
