### ISSUE TITLE
Location with delay of 6 Second?

### ISSUE THREAD

**Issue by IMHitesh** [paleksandrs/APScheduledLocationManager#17]
I want to get location after every 60 Seconds periodically, Everything working fine but, I have got location after 66 Seconds instead of 60 Seconds. Location accuracy is 100. I was also tried by using lower accuracy but no luck.

First Location Time: 12:52:57
Second Location Time: 12:54:03
Third Location Time: 12:55:09
Fourth Location Time: 12:56:15
Fifth Location Time: 12:57:21........so on

**Comment by paleksandrs** [comment]
It can take some time to get location, it also depends on accuracy
