### ISSUE TITLE
Will location updates happen in suspended state?

### ISSUE THREAD

**Issue by prakashidesign** [paleksandrs/APScheduledLocationManager#2]
This code will work in suspended state as well?

**Comment by paleksandrs** [comment]
It won't allow the app to enter the suspended state. The app will be always running.

**Comment by prakashidesign** [comment]
If we cleared the cache by double tapping the home button? then how it'll be work?

**Comment by paleksandrs** [comment]
If you force quit the app then it won't work as the app will be terminated.

**Comment by prakashidesign** [comment]
Ok thanks for the info.

**Comment by sebjvidal** [comment]
Is there a way to make this work when the app is terminated? For example, using geofences, if a user enters a larger region can this be activated to track specific location within the area and then stopped when the user leaves the geofence?

**Comment by prakashidesign** [comment]
Check this tutorial [link](https://www.raywenderlich.com/136165/core-location-geofencing-tutorial) for working in terminated state also.

**Comment by sebjvidal** [comment]
Thank you for the response, have been using Geofencing a bit already with a 300m radius around a given lat/long coordinate. When the didEnterRegion event is called, is that when I need to call the startUpdatingLocation function?

Not sure how clear my last post was so just to clarify, I'd like to only monitor the location updates when inside a Geofence. When outside of the Geofence, I don't care what goes on. Only want specific location inside 300m radius Geofence. Thanks :)
