### ISSUE TITLE
Execution stops after some hours

### ISSUE THREAD

**Issue by jpintor14** [paleksandrs/APScheduledLocationManager#20]
I add an APScheduledLocationManager in my project, it works ok, but I have realized that its stops after some time. The last location is registered about three hours after the timer was fired.
In that three hours I moved with the device. I stopped to move and later, 8 hours later, the background execution was not working. I don't know if it stops after three, five or even more hours

Any idea about that?

I am using an iPhone with iOS 12.1.4, and the code is the next:

`var manager = APScheduledLocationManager(delegate: self)`
`manager.startUpdatingLocation(interval: 150, acceptableLocationAccuracy: 50)`
`
    func scheduledLocationManager(_ manager: APScheduledLocationManager, didUpdateLocations locations: [CLLocation]) {
        //send location
    }`

Thanks in advance

**Comment by paleksandrs** [comment]
I haven't tested on iOS 12. There was another issue related to locking the device: https://github.com/paleksandrs/APScheduledLocationManager/issues/14

Maybe it will help

**Comment by jpintor14** [comment]
Ok, I will test it decreasing the interval and increasing the location accuracy's distance.

Thanks, I will bring back the results.

**Comment by jpintor14** [comment]
I can confirm that, with a 60 seconds interval it works ok at least for 12 years
