### ISSUE TITLE
Not getting location 

### ISSUE THREAD

**Issue by ErAshu** [paleksandrs/APScheduledLocationManager#21]
Not getting location if app terminates or Forcefully killed.

**Comment by paleksandrs** [comment]
And you shouldn't. There is no such option

**Comment by ErAshu** [comment]
kindly upgrade this for swift 5.x and solve this issue (when the app terminates from background).

**Comment by paleksandrs** [comment]
It is impossible to get location updates when the app is terminated

**Comment by ErAshu** [comment]
Then which method is called by WhatApp. WhatsApp is sending location everytime if you terminates the app. Try with live location sharing.
