### ISSUE TITLE
APScheduledLocationManager is not called when n = 20 or higher

### ISSUE THREAD

**Issue by mn288** [paleksandrs/APScheduledLocationManager#3]
when
self.manager.startUpdatingLocation(interval: 20, acceptableLocationAccuracy: 100)
and the app enters background mode, the APScheduledLocationManager won't run

but when
self.manager.startUpdatingLocation(interval: 2, acceptableLocationAccuracy: 100)
the APScheduledLocationManager works nicely

Why?

**Comment by mn288** [comment]
when            
**self.manager.startUpdatingLocation(interval: 20, acceptableLocationAccuracy: 100)**
and the app enters background mode, the APScheduledLocationManager won't run

but when
            **self.manager.startUpdatingLocation(interval: 2, acceptableLocationAccuracy: 100)**
the APScheduledLocationManager works nicely

Why?

**Comment by paleksandrs** [comment]
The provided example app is using 60 second interval and it is working. Make sure you enabled Background Modes.

**Comment by mn288** [comment]
Thank you, it was CLActivityType of the manager, I made it .automotiveNavigation and waited next to the debugger.. silly me :) 

Great work by the way
