### ISSUE TITLE
[!] Unable to find a specification for 'APScheduledLocationManager'

### ISSUE THREAD

**Issue by tejasverixo** [paleksandrs/APScheduledLocationManager#4]
Hi iam trying Installation using  CocoaPods but its not working. 
> Error : [!] Unable to find a specification for 'APScheduledLocationManager'
Can you please help me to fix this.

**Comment by paleksandrs** [comment]
This issue is related to CocoaPods not `APScheduledLocationManager` itself. I believe you have some issues with pod master repo. Check stackoverflow.
