### ISSUE TITLE
Using didUpdateLocations to send location to server

### ISSUE THREAD

**Issue by BrandonMayU** [paleksandrs/APScheduledLocationManager#9]
I am use the didUpdateLocations func to send the data to my firebase server. Before I sent data to the server I just printed the users location to the console in 5 second intervals. Everything was working fine however once I stopped printing the current location and instead sent it to firebase the didUpdateLocations func seemed to be called a 1000 times per second rather than every 5 seconds why is this?

**Comment by paleksandrs** [comment]
Not sure what it easy. Check your code and look at the example provided
